\section{Introduction}
This is a compelling introduction. 

Contributions\fix{placeholder language}:
\begin{itemize}
\item First in situ library designed with a fully hybrid distributed-memory, shared-memory parallel architecture that runs portably on many-core architectures. 
\item Flexible in situ framework that easily enables custom analysis (filters). \fix{weave filters from different runtimes together}
\item Light weight integrations and a minimally expressive api (most operations have defaults).
\end{itemize}


related work

staying tru to the requirements of strawman...

